# Build Lambda ZIP for s3 (saves the file as function.zip)

name: Python Build
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python 
        uses: actions/setup-python@v4        
      - name: create and activate venv
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip          
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: ZIP dependencies layers
        run: |
          cd venv/lib/python3.11/site-packages/
          zip -r9 $ {{ github.workspace }}/function.zip
