# Build Lambda ZIP for s3 (saves the file as function.zip)

name: Python Build
on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  build:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Python 
        uses: actions/setup-python@v4        
      
      - name: Python command
        run: |
          python -m venv env
          source venv/bin/activate
          python -m pip install --upgrade pip          
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          echo "VIRTUAL ENV:" $VIRTUAL_ENV
     
      - name: ZIP dependencies layers
        run: |
          cd $VIRTUAL_ENV/lib/python3.11/site-packages/
          zip -r9 ${{ github.workspace }}/function.zip .
      
      - name: ZIP app
        run: |
          zip -g ${{ github.workspace }}/function.zip -r ${{ github.workspace }}/app
                 
                  
      - name: Upload build artifact
        uses: actions/upload-artifact@v3
        with:
          name: Lambda function package
          path: ${{ github.workspace }}/function.zip
